services:
  postgres:
    image: postgres:16
    container_name: mist-postgres
    restart: always
    environment:
      POSTGRES_USER: mist_user
      POSTGRES_PASSWORD: mist_password
      POSTGRES_DB: mist_db
    ports:
      - "5433:5432"
    volumes:
      - mist_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mist-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mist_postgres_data:
  rabbitmq_data: